### PR TITLE
Developer portal

### PR DESCRIPTION
**Pull request by cgcardona**

### CODE REVIEW

**Comment by schancel** [comment]
This is looking good.  Let's proceed in this direction, but the spec and workgroups should be split up so that appropriate content can be given to the BCTF or C2 or whatever we want to call it.  There's the code-of-conduct, the ettiquette, and some other information about the workgroups that need to be visible.

**Comment by cgcardona** [comment]
Sounds good. I'll look in to that.

**Comment by schancel** [comment]
Not sure where the merge conflict came from?

**Comment by cgcardona** [comment]
I'm not seeing a merge conflict.

**Comment by schancel** [comment]
@brad1121 You want to merge this before or after your header changes?

**Comment by schancel** [comment]
What command did you run?

image

**Comment by brad1121** [comment]
@schancel Do this before, I can see there are going to be some conflicts which I think will be easier to sort out from my side than this one.

**Comment by brad1121** [comment]
The new pages will also need to be changed to fit the new header format/layout.

**Pull request merged**
