### PR TITLE
Created green bitcoin cash logos

### PR DESCRIPTION
**Pull request by CustomCommand**

### CODE REVIEW

**Comment by CustomCommand** [comment]
which one exactly? I also forget to rename the files that had the word orange in them. Please inform me to apply a fix.

**Comment by merc1er** [comment]
@maplesyrupsucker what do you think about this?

**Comment by maplesyrupsucker** [comment]
I'm afraid due to my employment at Bitcoin.com, and the company's decision to use green over orange for Bitcoin Cash, that my opinion won't be seen as objective amongst the workgroup. Afraid I have to bow out on this for the time being.

**Comment by merc1er** [comment]
@CustomCommand as mentioned on Telegram, the owner of the domain is not willing to host green logos.
Consider using https://bitcoinbch.com/resources/logos.html or other resources instead.

**Comment by imaginaryusername** [comment]
This is a terrible decision that will definitely come back to bite the credibility of bitcoincash.org down the road.

**Comment by zquestz** [comment]
Green logo's are not going to magically go away. By hosting them at bitcoincash.org as an optional set of logos it would reduce the variety of logos we see today that all have differing shades of green.

We have 2 options.

1) Say no to green on bitcoincash.org and have tons of other people make green logos that all look different and have different shades of green, fragmenting the logo space even more.

2) Offer green downloads on bitcoincash.org as an optional download with orange being recommended and hopefully get people on board with just 2 colors orange and a good shade of green.

There is no world where the green logos disappear, I hope the team will reconsider.

**Comment by BigBlockIfTrue** [comment]
As an orange logo supporter, I agree with @zquestz 

The multicoin ecosystem has a practical need for an option to show Bitcoin and Bitcoin Cash alongside each other in different colours. It makes sense for bitcoincash.org to offer such a variant option. The site and main logos can (and imo should) remain orange.

As an example from personal experience, when I prepare [a graph like this](https://honest.cash/v2/BigBlockIfTrue/bitcoin-cash-inflation-control-is-working-fine-6358), I draw an orange line and a green line, instead of two orange lines. Despite my ideological agreement with and preference for orange, here I chose green for practical reasons. I see no reason to not facilitate this.

**Pull request closed without merging**
