### PR TITLE
Add May 2019 upgrade information

### PR DESCRIPTION
**Pull request by Mengerian**

### CODE REVIEW

**Comment by Mengerian** [comment]
@Corbin @BUYMERCIER Please have a look.

I have included all the required information. The only issue is that I think the layout should be tweaked to make the notice more prominent. With the website redesign, the formatting has changed completely from the last Upgrade notice.

It also required adding two fields to the translation file, I did only the English portion. So those two items will need to be sent to translation.

**Comment by Mengerian** [comment]
Idea: while sending the new fields to translation, may also be a good idea to send the next few upgrade dates to translation also. That way we will be ready for next time.

the next fields would be:
  date-2019-11-15: "November 15th, 2019"
  date-2020-05-15: "May 15th, 2020"
  date-2020-11-15: "November 15th, 2020"
  date-2021-05-15: "May 15th, 2021"

**Comment by maplesyrupsucker** [comment]
@BUYMERCIER can you spend some time trying to make this a bit more prominent? Perhaps including a notice in header + increasing font size on notification bar?

**Comment by Mengerian** [comment]
@maplesyrupsucker Shall we merge it as-is for now, and work on making it more prominent later?

I think it would be good to get the information out there.

**Comment by Mengerian** [comment]
The new font size looks good! thanks @BUYMERCIER

**Comment by BUYMERCIER** [comment]
I haven't had time to really work on this, I still need to do something with the notification bar. In the meantime, feel free to merge this @Mengerian 👍. I'll submit another PR with improvements

**Comment by Mengerian** [comment]
OK, thanks @BUYMERCIER , I will merge it.

**Pull request merged**
