### PR TITLE
[wg] Create Payment Protocol workgroup

### PR DESCRIPTION
**Pull request by Mengerian**

### CODE REVIEW

**Comment by KarolTrzeszczkowski** [comment]
> In the meantime, please add your names in comments to the PR, if you want to be listed in the workgroup doc.

Licho

**Comment by markmeson** [comment]
> > In the meantime, please add your names in comments to the PR, if you want to be listed in the workgroup doc.
bchcoffee

**Comment by bitjson** [comment]
👋

**Comment by bitjson** [comment]
Some things I totally forgot during the call:
BitPay's paypro spec handles the "signing risk" well now – the wallet sends the unsigned transaction to the server, and any errors are reported to the wallet before the wallet signs. So it both prevents payment errors and avoids leaving the wallet in a vulnerable position. See: https://bitpay.com/docs/payment-protocol

It's also worth noting that an important feature for merchants is paypro interoperability with other cryptocurrencies. Most of the crypto payment processors accept payments on multiple networks, and maintaining a unique paypro infrastructure for each is expensive.

**Comment by Mengerian** [comment]
Added Bitpay spec as a reference
Added Licho and bchcoffee to "interested parties" as requested

**Comment by jsmith-dev** [comment]
Julian Smith

**Comment by Mengerian** [comment]
This group never really took off, so I'm closing the PR for now.

**Pull request closed without merging**
