### PR TITLE
Add Bitcoin Cash Node to upgrade compatible implementations

### PR DESCRIPTION
**Pull request by sickpig**
Built on top of #484 to avoid merge conflicts

### CODE REVIEW

**Comment by sickpig** [comment]
Hey @Mengerian @jasonbcox,

I just discovered that the owner of the bitcoincash.org 
(@deadalnix) thinks that BCHN is ["very hostile and threaten to fork"](https://youtu.be/lHGnfZWu1eU?t=10919) and for that reason it won't be listed among the list of compatible clients.

Just wanna to point out that this is merely a political play in my book. Both BCHD and BCH Unlimited are exactly the same of BCHN when it comes to the set of features needed for today's upgrade.

All the 3 clients implement all the needed stuff but IFP. So there's no technical reason to not include BCHN.

It had been better to say it loud and clear since the beginning that there wasn't any intention to merge this PR rather than keep it stalled here w/o 0 feedback. 

Not very professional if you ask me.

**Comment by georgedonnelly** [comment]
> Not very professional if you ask me.

Andrea, we are doing the best job we can with the limited resources available to us. I would counter that it is also not very professional to throw rocks at guys who are working past their limits, especially on the day of a major network upgrade.

Thank you everyone for your patience. We aim to respond to all requests within a reasonable time frame.

**Comment by jasonbcox** [comment]
I agree, this is poor form from @sickpig. This behavior from you is going to get you ignored by everyone who is focusing on hard work rather than wasting their time with political games about who gets listed on a website.

BCHN needs to grow up before a PR like this will be considered.

**Comment by ftrader** [comment]
> The project does not have any degree of prolonged activity and provides questionable, if any, value to Bitcoin Cash.

Keep merging our improvements while you maintain we do not provide any value, Jason.

**Comment by pokkst** [comment]
I sense a lot of projection coming from ABC. Hmmmm.

**Pull request closed without merging**
