### PR TITLE
Remove Yenom wallet

### PR DESCRIPTION
**Pull request by Mengerian**
The project appears to be defunct

### CODE REVIEW

**Comment by georgedonnelly** [comment]
I emailed the google play store contact address 21 Jun, almost 48 hours ago, no reply yet.

**Comment by merc1er** [comment]
Thanks! Let’s remove it ASAP to avoid having more people lose funds!

**Comment by Mengerian** [comment]
For the record, here's an announcement by Yenom that the wallet is shut down: https://twitter.com/yenom_wallet/status/1285016199516925952

English via Google Translate:
"Thank you for using Yenom.
The service will be terminated as of the end of December 2020.

Since both iOS and Android services will be terminated, please move to another company's wallet or exchange."

**Comment by Mengerian** [comment]
Actually, they did have an English Tweet also: https://twitter.com/Yenom_wallet_en/status/1285016979103862785

**Pull request merged**
